[tool.poetry]
name = "script"
version = "0.1.0"
description = ""
authors = ["htcmw <htcmw93@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
yt-dlp = "^2025.1.26"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

